#!/bin/bash
# Purpose: Application Health Check For Zero Down Time

dns_name="localhost"
health_check_path="/api/v1/users/"

# This IPV4 Address of machine
echo "domain name is "$dns_name""

# DNS+HealthCheck PAth combined
echo "health check path is "$dns_name""$health_check_path""



# Services Status
echo "Restarting UWSGI"
systemctl restart uwsgi
sleep 10
echo "UWSGI STATUS" && systemctl is-active uwsgi

sleep 5
echo "Restarting SUPERVISOR"
systemctl restart supervisor
sleep 5
echo "SUPERVISOR STATUS" && systemctl is-active supervisor

sleep 10
echo "Restarting NGINX"
systemctl restart nginx
sleep 5
echo "NGINX STATUS" && systemctl is-active nginx

# Wait Time For Application Up & Running
wait="60"
echo "Wait Time For Application Up & Running, Please wait "$wait" sec than Application Health Checks will begin ..."
# bash while loop
sleep "$wait"
echo "Checking Health Checks with curl let's see!"




# Now health checking
curl ""$dns_name""$health_check_path""

while true
do
  response=$(curl -I ""$dns_name""$health_check_path"" | head -n1 | awk '{print $2}')

     echo "This is application Status Code via Curl "$response""

    if [ $response -eq 200 ] ; then
    echo "$(date -u) app is available"
    exit 0

      else
      echo "$(date -u) app is unavailable"
      exit 1
  fi


done

#END
