#!/bin/bash
# Purpose: Application Health Check For Zero Down Time

dns_name="localhost"
health_check_path="/api/v1/users/"

# This IPV4 Address of machine
echo ""$dns_name""

# DNS+HealthCheck PAth combined
echo ""$dns_name""$health_check_path""


# Wait Time For Application Up & Running
wait="600"
echo "Wait Time For Application Up & Running, Please wait "$wait" sec than Application Health Checks will begin ..."
# bash while loop
while [ $wait -gt 0 ]
do
        sleep 1
        echo $wait
        let wait=wait-1
done
echo "Checking Health Checks with curl let's see!"




# Now health checking
curl ""$dns_name""$health_check_path""

while true
do
  response=$(curl -I ""$dns_name""$health_check_path"" | head -n1 | awk '{print $2}')

     echo "This is application Status Code via Curl "$response""

    if [ $response -eq 200 ] ; then
    echo "$(date -u) app is available"
    exit 0

      else
      echo "$(date -u) app is unavailable"
      exit 1
  fi


done

#END
