#!/bin/bash
#OS: Ubuntu-16-18-LTS

apt update -y
apt install -y curl

curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh

 systemctl start docker
 systemctl enable docker

docker network ls

docker network create --driver=bridge cloudelligent

docker run --name jenkins --network=cloudelligent -d --user=root -v ~/jenkins:/var/jenkins_home -p 8080:8080 --restart unless-stopped jenkins/jenkins:2.176.1


#1 
mkdir -p ~/ssl/certs

#2 
mkdir -p ~/nginx/conf.d

#3 
openssl genrsa -des3 -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem

sleep 5
echo '
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = 192.168.1.10
' > v3.ext

sleep 5
openssl req -new -sha256 -nodes -out server.csr -newkey rsa:2048 -keyout server.key
openssl x509 -req -in server.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out server.crt -days 500 -sha256 -extfile v3.ext

#Importing CA in Ubuntu
apt-get install ca-certificates -y
cp server.crt /usr/local/share/ca-certificates/
dpkg-reconfigure ca-certificates
#update-ca-certificates

mv server.key ~/ssl/certs
mv server.crt ~/ssl/certs
mv rootCA.pem ~/ssl/certs
mv rootCA.key ~/ssl/certs
mv rootCA.srl ~/ssl/certs
mv v3.ext ~/ssl/certs
mv server.csr ~/ssl/certs
rm -rf ~/get-docker.sh


#4
cd ~/nginx/conf.d

#5
apt update -y  2> /dev/null 
apt install -y vim 2> /dev/null
yum update -y  2> /dev/null 
yum install -y vim 2> /dev/null

#6
echo '
server {
  listen 80;
  server_name 192.168.1.10;
  return 301 https://$host$request_uri;
}
server {
  server_name 192.168.1.10;
  listen 443 ssl;
  ssl_certificate /etc/ssl/certs/server.crt;
  ssl_certificate_key /etc/ssl/certs/server.key;
  
  
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers    TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:TLS-AES-128-GCM-SHA256:HIGH:!aNULL:!MD5; 
 
  
  
location / {
    proxy_set_header        Host $host:$server_port;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_redirect http:// https://;
    proxy_pass              http://jenkins:8080;
    # Required for new HTTP-based CLI
    proxy_http_version 1.1;
    proxy_request_buffering off;
  
       }
}' >  ~/nginx/conf.d/server.conf

#7
docker run --name nginx --network=cloudelligent --restart unless-stopped -v ~/ssl/certs:/etc/ssl/certs -v ~/nginx/conf.d:/etc/nginx/conf.d -p 443:443 -p 80:80 -d nginx




#END
