#!/bin/bash
# Purpose nginx simple reverse proxy
# https://docs.kuzzle.io/core/2/guides/essentials/ssl-support/



###
#Nginx
####
# Nginx Container



#1
mkdir -p ~/nginx/conf.d



#2
cd ~/nginx/conf.d


#3
echo '
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}


server {
  listen 80;
  server_name kuzzle.local;

  location / {
    proxy_pass http://kuzzle_kuzzle_1:7512;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}

}

' >  ~/nginx/conf.d/server.conf

#4
docker run --name nginx --network=kuzzle_default --restart unless-stopped -v ~/nginx/conf.d:/etc/nginx/conf.d -p 80:80 -d nginx




#END
