#!/bin/bash
# https://nickjanetakis.com/blog/docker-tip-79-saving-a-postgres-database-in-a-docker-image
# https://www.postgresqltutorial.com/postgresql-show-databases/#:~:text=Use%20%5Cl%20or%20%5Cl%2B%20in,pg_database%20to%20get%20all%20databases.

docker network create postgres

#Postgres Setup
docker run --name postgres --network="postgres" -e POSTGRES_PASSWORD="12345678" -e POSTGRES_USER=asim -e POSTGRES_DB=mydb -e PGDATA=/var/lib/postgresql/data/pgdata -v /root/mount:/var/lib/postgresql/data -id postgres:latest

# Adminer Setup
docker run --link postgres:db --network="postgres" -p 8080:8080 -id adminer

#END


#!/bin/bash
# https://nickjanetakis.com/blog/docker-tip-79-saving-a-postgres-database-in-a-docker-image
# https://www.postgresqltutorial.com/postgresql-show-databases/#:~:text=Use%20%5Cl%20or%20%5Cl%2B%20in,pg_database%20to%20get%20all%20databases.

docker network create postgres

#Postgres Setup
docker run --name postgres --network="postgres" -e POSTGRES_PASSWORD="12345678" -id quickbooks2018/postgres

# Adminer Setup
docker run --link postgres:db --network="postgres" -p 8080:8080 -id adminer

# user ---> postgres
# password ---> 12345678
# Do not give DB name

####################################################################################################################

#!/bin/bash

#Postgres Setup
docker run --name postgres --network="postgres" -e POSTGRES_PASSWORD="12345678" -p 5432:5432 -id quickbooks2018/postgres

# Adminer Setup
docker run --link postgres:db --network="postgres" -p 8080:8080 -id adminer

#END
