#!/bin/bash
# Purpose: Monitoring
# OS Ubuntu
# Maintainer DevOps Muhammad Asim <quickbooks2018@gmail.com>

# Docker Installation
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh      2>&1 > /dev/null
rm -rf get-docker.sh

# Docker Compose Installation

curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version

# Zabbix Default Password
#Admin
#abbix


# Docker Network
docker network create zabbix --attachable

# Start empty MySQL server instance
# docker volume create zabbix-mysql
# docker volume create zabbix-mysql-conf
# docker run --name mysql-server -t  --restart unless-stopped \
#       -e MYSQL_DATABASE="zabbix" \
#       -e MYSQL_USER="zabbix" \
#       -e MYSQL_PASSWORD="123456789" \
#       -v zabbix-mysql:/var/lib/mysql \
#       -v zabbix-mysql-conf:/etc/mysql/conf.d \
#       --network "zabbix" \
#       -e MYSQL_ROOT_PASSWORD="root_pwd" \
#       -id mysql:latest \
#       --character-set-server=utf8 --collation-server=utf8_bin \
#       --default-authentication-plugin=mysql_native_password

###############################
# External MYSQL DATABASE SETUP
###############################

# sudo mysql -uroot -p

# mysql> create database zabbix character set utf8 collate utf8_bin;


# CREATE USER 'asim'@'%' IDENTIFIED BY 'Asim1982!@#$%';


# GRANT ALL PRIVILEGES ON zabbix.* to asim@'%';

# FLUSH PRIVILEGES;

# exit


sleep 10
# Start Zabbix Java gateway instance
docker run --name zabbix-java-gateway -t \
      --restart unless-stopped \
      --network "zabbix" \
      -d zabbix/zabbix-java-gateway:latest


sleep 10
# https://hub.docker.com/r/zabbix/zabbix-server-mysql
# Start Zabbix server instance and link the instance with created MySQL server instance
docker volume create zabbix-conf
docker run --name zabbix-server -t \
      -e DB_SERVER_HOST="172.31.3.20" \
      -e DB_SERVER_PORT="3306" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="asim" \
      -e MYSQL_PASSWORD='Asim1982!@#$%' \
      -e ZBX_JAVAGATEWAY="zabbix-java-gateway" \
      -v zabbix-conf:/etc/zabbix \
      -h zabbix-server \
      --network "zabbix" \
      --link zabbix-java-gateway:zabbix-java-gateway \
      -p 10051:10051 \
      --restart unless-stopped \
      -d zabbix/zabbix-server-mysql:latest

   # -e MYSQL_ROOT_PASSWORD="123456789" \

sleep 10
# Start Zabbix web interface and link the instance with created MySQL server and Zabbix server instances
docker run --name zabbix-web-nginx-mysql -t \
      -e DB_SERVER_HOST="172.31.3.20" \
      -e DB_SERVER_PORT="3306" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="asim" \
      -e MYSQL_PASSWORD='Asim1982!@#$%' \
      --network "zabbix" \
      --link zabbix-server:zabbix-server \
      -p 80:8080 \
      --restart unless-stopped \
      -d zabbix/zabbix-web-nginx-mysql:latest

      # -e MYSQL_ROOT_PASSWORD="123456789" \

sleep 10
# Zabbix-Agent
docker run --name zabbix-agent --network="zabbix" --restart unless-stopped -id zabbix/zabbix-agent:latest


docker volume create grafana-etc
docker volume create grafana
docker run -id --name=grafana --network zabbix -v  grafana:/var/lib/grafana -v grafana-etc:/etc/grafana -p 3000:3000 grafana/grafana:latest
docker exec grafana grafana-cli plugins install alexanderzobnin-zabbix-app
docker restart grafana

#END

# Addtional Notes
# Zabbix API
# http://privateip/api_jsonrpc.php      # Eg: http://10.20.1.20/api_jsonrpc.php
# http://127.0.0.1/zabbix/api_jsonrpc.php # Eg: http://172.31.10.4/zabbix/api_jsonrpc.php

# http://172.31.15.234/zabbix/api_jsonrpc.php

# Docker remove all containers
# docker rm -f $(docker ps -aq)
