#!/bin/bash
#Purpose: Monitoring
#OS AmazonLinux/Ubuntu
#Maintainer DevOps Muhammad Asim <quickbooks2018@gmail.com>
# https://github.com/quickbooks2018/Terraform-V-12/tree/master/terraform.v12/vpc%2Bec2-zabbix%2Bec2-grafana

# Docker Installation
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh      2>&1 > /dev/null
rm -rf get-docker.sh
yum install -y docker 2>&1 > /dev/null
systemctl start docker
systemctl enable docker

# Docker Compose Installation

curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version

# Zabbix Default Password
Admin
zabbix


# Docker Network
docker network create zabbix --attachable

sleep 10
# Start empty MySQL server instance
docker volume create zabbix-mysql
docker volume create zabbix-mysql-conf
docker run --name mysql-server -t  --restart unless-stopped \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="123456789" \
      -v zabbix-mysql:/var/lib/mysql \
      -v zabbix-mysql-conf:/etc/mysql/conf.d \
      --network "zabbix" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      -id mysql:latest \
      --character-set-server=utf8 --collation-server=utf8_bin \
      --default-authentication-plugin=mysql_native_password


sleep 10
# Start Zabbix Java gateway instance
docker run --name zabbix-java-gateway -t \
      --restart unless-stopped \
      --network "zabbix" \
      -d zabbix/zabbix-java-gateway:latest


sleep 10
# Start Zabbix server instance and link the instance with created MySQL server instance
docker volume create zabbix-conf
docker run --name zabbix-server -t \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="123456789" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      -e ZBX_JAVAGATEWAY="zabbix-java-gateway" \
      -v zabbix-conf:/etc/zabbix \
      -h zabbix-server \
      --network "zabbix" \
      --link mysql-server:mysql \
      --link zabbix-java-gateway:zabbix-java-gateway \
      -p 10051:10051 \
      --restart unless-stopped \
      -d zabbix/zabbix-server-mysql:latest



sleep 10
# Start Zabbix web interface and link the instance with created MySQL server and Zabbix server instances
docker run --name zabbix-web-nginx-mysql -t \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="123456789" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      --network "zabbix" \
      --link mysql-server:mysql \
      --link zabbix-server:zabbix-server \
      -p 80:8080 \
      --restart unless-stopped \
      -d zabbix/zabbix-web-nginx-mysql:latest

sleep 10
# Zabbix-Agent
docker run --name zabbix-agent --network="zabbix" -id zabbix/zabbix-agent:latest

# Docker remove all containers
# docker rm -f $(docker ps -aq)



#!/bin/bash
#Purpose: Monitoring
#App: Grafana
#OS AmazonLinux/Ubuntu
#Maintainer DevOps Muhammad Asim <quickbooks2018@gmail.com>

# Default Password

admin 
admin

# Docker Installation
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh      2>&1 > /dev/null
rm -rf get-docker.sh
yum install -y docker 2>&1 > /dev/null
systemctl start docker
systemctl enable docker

# Docker Compose Installation

curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version

MONITORING=`docker network ls | awk '{print $2}' | grep -i "zabbix"`
if [ "0" == "$?" ]
then
  echo -e "\n Hey! docker network "$MONITORING" exists \n"
  else
    docker network create zabbix
    fi

docker volume create grafana-etc
docker volume create grafana
docker run -id --name=grafana --network zabbix -v  grafana:/var/lib/grafana -v grafana-etc:/etc/grafana -p 3000:3000 grafana/grafana:latest
docker exec grafana grafana-cli plugins install alexanderzobnin-zabbix-app
docker restart grafana

#END

# Addtional Notes
# Zabbix ---> import 5363
# Zabbix API
# http://privateip/api_jsonrpc.php      # Eg: http://10.20.1.20/api_jsonrpc.php
# http://127.0.0.1/zabbix/api_jsonrpc.php # Eg: http://172.31.10.4/zabbix/api_jsonrpc.php

http://172.31.15.234/zabbix/api_jsonrpc.php
