version: '3'

services:
  app:
    build:
      context: .
    restart: unless-stopped  

    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  
  nginx:
      build:
        context: .
        dockerfile: DockerfileNginx
      restart: unless-stopped  
      ports:
      - "80:80"  

    
volumes:
  pgdata: