#!/bin/bash
# Purpose: Kafka Cluster In Kubernetes
# Maintainer DevOps <Muhammad Asim <quickbooks2018@gmail.com>

# Kubectl Installation
curl -# -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
chmod +x ./kubectl
mv ./kubectl /usr/local/bin/kubectl
kubectl version --client

# Kind Installation
# Latest Version
# 
curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.9.0/kind-$(uname)-amd64"
# curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
# curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
chmod +x ./kind
mv ./kind /usr/local/bin

# Cluster Creation

 kind create cluster --name cloudgeeks-ca --image kindest/node:v1.19.0


 kubectl cluster-info --context kind-cloudgeeks-ca

#END
